### ISSUE TITLE
[Feature request] Only ask for path to game folder, not stories

### ISSUE THREAD

**Issue by suzicurran** [suzicurran/ExomodLoader#1]
**Is your feature request related to a problem? Please describe.**
Many players won't know where the Stories file is. Asking them for their game folder (example: "C:\Program Files (x86)\Steam\steamapps\common\Exocolonist") is probably a better experience. It's also what they get if they go to Properties > Local Files > Browse in Steam.

**Describe the solution you'd like**
Instead of asking the user for the path to their game's Stories folder, ask for (and store) the path to their Exocolonist game folder.
Append Exocolonist_Data/StreamingAssets/Stories as necessary to paths.

**Describe alternatives you've considered**
¯\\_(ツ)_/¯ Not doing this because maybe no one will care?

**Additional context**
This requires a schema update for user settings. This is a great time to establish a pattern for the versioning system, including backwards-comparability / auto-upgrades.

**Comment by eskolnik** [comment]
I'm taking this on now. One question / note - I'm not sure this actually requires a schema update. The setting we store can still be the full path to the stories folder, we'd just append the stories path to the game folder path provided by the user. I could do the schema change anyway, if preferable, but I don't think it's necessary.

**Comment by suzicurran** [comment]
Yeah, that works for me!
